#### Agreement
agreement_proto_id=100

#### StateMachine
babel.port=34000
initial_membership=127.0.0.1:34000,127.0.0.1:34001,127.0.0.1:34002

#### App
server_port=35000

##### General
babel.interface=lo

# Paxos tuning
paxos.max_outstanding=100
paxos.proposal_interval_ms=1
paxos.accept_retry_ms=200
paxos.accept_retry_backoff=2.0
paxos.disable_persistence=true